# Generated by Django 3.1.7 on 2021-03-26 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('creationDate', models.DateField(auto_now_add=True)),
                ('availablity', models.BooleanField()),
                ('lastUpdated', models.DateField(auto_now=True)),
                ('validity', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('creationDate', models.DateField(auto_now_add=True)),
                ('availablity', models.BooleanField()),
                ('ffile', models.FileField(default='', upload_to='')),
                ('lastUpdated', models.DateField(auto_now=True)),
                ('validity', models.BooleanField()),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serverSide.directory')),
            ],
        ),
        migrations.CreateModel(
            name='SectionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('PE', 'procedure'), ('PY', 'property'), ('LE', 'lemma'), ('AS', 'assertion'), ('IR', 'invariant'), ('EC', 'precondition'), ('OC', 'postcondition')], max_length=2)),
                ('lastUpdated', models.DateField(auto_now=True)),
                ('validity', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='StatusSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PV', 'proved'), ('IV', 'invalid'), ('CE', 'counterexample'), ('UC', 'unchecked')], default='UC', max_length=2)),
                ('lastUpdated', models.DateField(auto_now=True)),
                ('validity', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('login', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('lastUpdated', models.DateField(auto_now=True)),
                ('validity', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='StatusData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusDataField', models.CharField(max_length=1000)),
                ('lastUpdated', models.DateField(auto_now=True)),
                ('validity', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serverSide.user')),
            ],
        ),
        migrations.CreateModel(
            name='FileSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('creationDate', models.DateField(auto_now_add=True)),
                ('lastUpdated', models.DateField(auto_now=True)),
                ('validity', models.BooleanField()),
                ('category', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='serverSide.sectioncategory')),
                ('parentFile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serverSide.file')),
                ('parentSection', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='serverSide.filesection')),
                ('status', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='serverSide.statussection')),
                ('statusData', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='serverSide.statusdata')),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serverSide.user'),
        ),
        migrations.AddField(
            model_name='directory',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serverSide.user'),
        ),
    ]
