# Generated by Django 3.1.7 on 2021-03-27 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serverSide', '0003_auto_20210327_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='directory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='serverSide.directory'),
        ),
    ]
