# Generated by Django 3.1.7 on 2021-03-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverSide', '0005_auto_20210327_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='ffile',
            field=models.FileField(upload_to=''),
        ),
    ]
