# Generated by Django 3.1.7 on 2021-03-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverSide', '0007_auto_20210328_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesection',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='statussection',
            name='status',
            field=models.CharField(max_length=30),
        ),
    ]
