# Generated by Django 3.1.7 on 2021-03-28 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serverSide', '0010_auto_20210328_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesection',
            name='category',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='serverSide.sectioncategory'),
            preserve_default=False,
        ),
    ]
