# Generated by Django 3.1.7 on 2021-03-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverSide', '0012_auto_20210328_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='creationDate',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='directory',
            name='lastUpdated',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='file',
            name='creationDate',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='file',
            name='lastUpdated',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='filesection',
            name='creationDate',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='filesection',
            name='lastUpdated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sectioncategory',
            name='lastUpdated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='statusdata',
            name='lastUpdated',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='statussection',
            name='lastUpdated',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastUpdated',
            field=models.DateTimeField(),
        ),
    ]
