# Generated by Django 3.1.7 on 2021-03-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverSide', '0013_auto_20210328_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesection',
            name='lastUpdated',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sectioncategory',
            name='lastUpdated',
            field=models.DateTimeField(),
        ),
    ]
