# Generated by Django 3.1.7 on 2021-03-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverSide', '0017_directory_parentdirectory'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='path',
            field=models.TextField(blank=True),
        ),
    ]
