# Generated by Django 3.1.7 on 2021-03-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverSide', '0018_directory_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='level',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
