# Generated by Django 3.1.7 on 2021-04-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverSide', '0019_directory_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesection',
            name='sectBegin',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='filesection',
            name='sectEnd',
            field=models.IntegerField(default=0),
        ),
    ]
