# Generated by Django 3.1.7 on 2021-05-01 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serverSide', '0021_auto_20210501_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='owner',
        ),
    ]
