# Generated by Django 3.1.7 on 2021-05-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverSide', '0022_remove_file_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectioncategory',
            name='validity',
            field=models.BooleanField(default=True),
        ),
    ]
